apiVersion: v2
name: prometheus-grafana-monitoring
description: Prometheus and Grafana monitoring solution using community charts
type: application
version: 0.1.0
appVersion: "v2.45.0"
keywords:
  - prometheus
  - monitoring
  - metrics
  - observability
  - grafana
  - alertmanager
home: https://prometheus.io/
sources:
  - https://github.com/prometheus-community/helm-charts
maintainers:
  - name: Joel Grant
    email: joelgrantdev@gmail.com
dependencies:
  - name: kube-prometheus-stack
    version: "61.7.2"
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-postgres-exporter
    version: "4.15.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: postgresql.enabled
